version: '3'
services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb_container
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
