version: '3'
services:
  couchdb:
    restart: always
    image: couchdb:latest
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - couchdb
    environment:
      - COUCHDB_URL=http://couchdb:5984

volumes:
  couchdb_data: